server:
  port: 8083

spring:
  application:
    name: ClaimsService

  datasource:
    url: jdbc:mysql://localhost:3306/claim_db
    username: root
    password: Root@123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/